### ISSUE TITLE
java-gateway is not enabled. State=started is not ensured.

### ISSUE THREAD

**Issue by DXist** [dj-wasabi/ansible-zabbix-javagateway#1]
There is no `enabled=yes` and unconditional`state=started` for service configuration.

**Comment by dj-wasabi** [comment]
Thanks, will take a look at it.

**Comment by dj-wasabi** [comment]
Hi,
Sorry for late reploy, but just pushed an fix for this.

**Comment by DXist** [comment]
Hi! Thank you so much!
